package com.healthcare.service;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.Date;

@Service
public class PdfExportService {

    public byte[] generateSymptomReportPdf(String symptoms, String aiResponse) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Paragraph title = new Paragraph("CareSync AI - Medical Assessment Report", titleFont);
            title.setAlignment(Paragraph.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            Font subFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            document.add(new Paragraph("Date: " + new Date().toString(), subFont));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("Reported Symptoms:", subFont));
            document.add(new Paragraph(symptoms));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("AI Preliminary Assessment:", subFont));
            // Basic stripping of markdown
            String cleanResponse = aiResponse.replaceAll("\\*\\*", "").replaceAll("##", "").replaceAll("#", "");
            document.add(new Paragraph(cleanResponse));

            document.add(new Paragraph(" "));
            Font disclaimerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10);
            document.add(new Paragraph("DISCLAIMER: This report is generated by an AI and is NOT medical advice. Always consult a qualified healthcare professional.", disclaimerFont));

            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            e.printStackTrace();
            return new byte[0];
        }
    }
}
 
